version: "3"

services:
  reverse-proxy:
    image: traefik:v2.1
    command:
    - --api.insecure=true
    - --providers.docker=true
    ports: 
    - 80:80
    - 8080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  api:
    build: .
    stop_signal: SIGINT
    labels:
    - traefik.http.routers.api.rule=PathPrefix(`/api/`)

  client:
    image: vtcs2304s19/blabber-client
    labels:
    - traefik.http.routers.cilent.rule=PathPrefix(`/`)

  mongo:
    image: mongo:4
    volumes:
    - mongo-data:/data/db


volumes:
  mongo-data:
