version: "3"

services:
  reverse-proxy:
    image: traefik:v2.1
    command:
    - --api.insecure=true
    - --providers.docker=true
    ports: 
    - 80:80
    - 8080:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  api:
    build: .
    stop_signal: SIGINT
    labels:
    - traefik.http.routers.api.rule=PathPrefix(`/api/`)
    environment:
      - DEBUG_METRICS=1

  client:
    image: vtcs2304s19/blabber-client
    labels:
    - traefik.http.routers.cilent.rule=PathPrefix(`/`)

  mongo:
    image: mongo:4
    volumes:
    - mongo-data:/data/db

  prometheus:
    image: prom/prometheus:v2.17.1
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:6.7.2
    volumes:
    - grafana-storage:/var/lib/grafana
    ports:
    - 3000:3000

volumes:
  mongo-data:
  grafana-storage:
